states = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. 'Swaziland')",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmen istan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

jobs = [
    'Accessory designer',
    'Advertising designer',
    'Animator',
    'Architect',
    'Art administrator',
    'Art therapist',
    'Artisan',
    'Arts administration',
    'Baker',
    'Ceramics artist',
    'Chief creative officer',
    'Colorist',
    'Comedian',
    'Concept Artist',
    'Curator',
    'Dancer',
    'Design director',
    'Design strategist',
    'Essayist',
    'Event planner',
    'Fashion designer',
    'Fine artist',
    'Floral designer',
    'Game designer',
    'Graphic designer',
    'Hairstylist',
    'Illustrator',
    'Interior designer',
    'Jewellery designer',
    'Lyricist',
    'Make-up artist',
    'Marine designer',
    'Media designer',
    'Musician',
    'Party planner',
    'Penciller',
    'Photographer',
    'Photojournalist',
    'Potter',
    'Production designer',
    'Sculptor',
    'Set decorator',
    'Set dresser',
    'Singer',
    'Tattoo artist',
    'Web designer',
    'Wedding planner',
    'Writer',
    'Arts Administrator',
    'Ballet dancer',
    'Corps de ballet',
    'Demi-soloist',
    'Principal dancer',
    'Soloist',
    'Ballet historian',
    'Ballet master',
    'Choreographer',
    'Dance critic',
    'Dance historian',
    'Dance notator',
    'Dance scholar',
    'Dance therapist',
    'Dancer',
    'Backup dancer',
    'Caller (dancing)',
    'Exotic dancer',
    'Majorette (dancer)',
    'Showgirl',
    'Taxi dancer',
    'Acrobat',
    'Actor',
    'Archimime',
    'Athlete',
    'Barker',
    'Beatboxer',
    'Benshi',
    'Bouffon',
    'Circus performer',
    'Clown',
    'Club Hostess/Host',
    'Comedian',
    'Dancer',
    'Drag queen',
    'Drag king',
    'DJ',
    'Emcee',
    'Filmmaker',
    'Flag throwing',
    'Flair bartender',
    'Flatulist',
    'Geisha',
    'Go-go dancer',
    'Harlequin',
    'Host',
    'Illusionist',
    'Impressionist',
    'Internet celebrity',
    'Itinerant poet',
    'Japanese idol',
    'Jester',
    'Kobzar',
    'Lirnyk',
    'Online streamer',
    'Magician',
    'Master of ceremonies',
    'Mime',
    'Minstrel',
    'Monologist',
    'Musician',
    'Painter',
    'Party princess',
    'Performer',
    'Photographer',
    'Podcaster',
    'Poet',
    'Promotional model',
    'Radio personality',
    'Rapper',
    'Rhapsode',
    'Ring girl',
    'Ringmaster',
    'Scop',
    'Shamakhi dancers',
    'Showgirl',
    'Showman',
    'Showrunner',
    'Singer',
    'Skomorokh',
    'Streamer',
    'Street performer',
    'Stunt performer',
    'Theatre practitioner',
    'TikToker',
    'TV celebrity',
    'Vedette',
    'Writer',
    'YouTuber',
    'Animator',
    'Cartoonist',
    'Tweener',
    'Casting director',
    'Cinematographer Chief',
    'Executive producer',
    'Film director',
    'Film producer',
    'Production manager',
    'Screenwriter',
    'Stunt coordinator',
    'Showrunner',
    'Television director',	
    'Television producer',	
    'Television program creator',
    'Actor',
    'Costume designer',
    'Lighting technician',
    'Make-up artist',
    'Reporter',
    'Newscaster',
    'Screenwriter',		
    'Video editor',		
    'Voice actor',	
    'Weatherman/woman',
    'Producer',
    'Director',
    'Playwright',
    'Dramaturge',
    'Scenic designer',
    'Scenographer',
    'Lighting designer',
    'Costume designer',
    'Set designer',
    'Sound designer',
    'Composer',
    'Music director',
    'Choreographer',
    'Movement Director',
    'Fight Director',
    'Intimacy Coordinator',
    'Actor',
    'Audio Engineer',
    'Backstage',
    'Carpenter and master carpenter',
    'Charge artist',
    'Dancer',
    'Electrician',
    'Fight Director',
    'Front of House Manager',
    'Intimacy director',
    'Hair and wig designer',
    'Lighting technician',
    'Master electrician',
    'Musician',
    'Painters',
    'Playbill writer',
    'Production manager',
    'Property master',
    'Publicist',
    'Sound Engineer',
    'Sound Technician',
    'Scenic artist',
    'Stagehands',
    'Stage manager',
    'ASM(Assistant Stage Manager)',
    'Technical director',
    'Theatrical technician',
    'Wardrobe supervisor',
    'Artistic director',
    'Theater manager',
    'Production Manager',
    'Music Director',
    'Technical Director',
    'Costume Shop Manager',
    'Marketing Director',
    'Public Relations Director',
    'Director of audience services',
    'Director of Development',
    'Director of special events',
    'Dramaturge',
    'Literary Manager',
    'Company Manager',
    'House manager',
    'Usher',
    'Ticketing ',
    'Crew chief',
    'Janitor',
    'Dresser',
    'Stage crew',
    'Fly crew',
    'Light Board Operator',
    'Spotlight Operator',
    'Call boy',
    'Wardrobe Crew',
    'Character actor',
    'Pantomime dame',
    'Stagehand',
    'Running crew',
    'Author',
    'Blogger',
    'Book coach',
    'Commissioning editor',
    'Copy editor',
    'Creative consultant',
    'Dog writer',
    'Freelancer',
    'Ghostwriter',
    'Griot',
    'Hack writer',
    'Infopreneur',
    'Investigative Journalist',
    'Journalist',
    'Literary editor',
    'Manuscript format',
    'Medical writing',
    'Novelist',
    'Poet',
    'Polygraph (author)',
    'Review',
    'Screenwriter',
    'Scribe',
    'Script coordinator',
    'Script doctor',
    'Scrivener',
    'Songwriter',
    'Speechwriter',
    'Staff writer',
    'Technical writer',
    'Website content writer',
    'Writer',
    'Arborist',
    'Beader',
    'Bobbin boy',
    'Construction worker',
    'Factory worker',
    'Feller',
    'Filling station attendant',
    'Foreman',
    'Miller',
    'Moldmaker',
    'Panel beater',
    'Patternmaker',
    'Plant operator',
    'Plumber',
    'Sawfiler',
    'Shop foreman',
    'Soaper',
    'Stationary engineer',
    'Welder',
    'Wheelwright',
    'Woodworkers',
    'Chief administrative officer',
    'Chief analytics officer',
    'Chief brand officer',
    'Chief business development officer',
    'Chief business officer',
    'Chief cloud officer',
    'Chief commercial officer',
    'Chief communications officer',
    'Chief compliance officer',
    'Chief content officer',
    'Chief creative officer',
    'Chief customer officer',
    'Chief data officer',
    'Chief design officer',
    'Chief digital officer',
    'Chief diversity officer',
    'Chief executive officer',
    'Chief experience officer',
    'Chief financial officer',
    'Chief gaming officer',
    'Chief genealogical officer',
    'Chief growth officer',
    'Chief human resources officer',
    'Chief information officer',
    'Chief information officer',
    'Chief information security officer',
    'Chief innovation officer',
    'Chief investment officer',
    'Chief knowledge officer',
    'Chief learning officer',
    'Chief legal officer',
    'Chief marketing officer',
    'Chief operating officer',
    'Chief people officer',
    'Chief privacy officer',
    'Chief process officer',
    'Chief product officer',
    'Chief reputation officer',
    'Chief research',
    'Chief restructuring officer',
    'Chief revenue officer',
    'Chief risk officer',
    'Chief scientific officer',
    'Chief security officer',
    'Chief services officer',
    'Chief solutions officer',
    'Chief strategy officer',
    'Chief supply chain officer',
    'Chief sustainability officer',
    'Chief technical officer',
    'Chief technology officer',
    'Chief technology security officer',
    'Chief visibility officer',
    'Chief visionary officer',
    'Chief web officer',
    'Bookbinder',
    'Cordwainer',
    'Corsetier',
    'Draper',
    'Dressmaker',
    'Embroiderer',
    'Glover',
    'Hatter',
    'Leatherworker',
    'Milliner',
    'Parachute rigger',
    'Quilter',
    'Sailmaker',
    'Seamstress',
    'Shoemaker',
    'Tailor',
    'Taxidermist',
    'Upholsterer',
    'A/B tester',
    'Application analyst',
    'Business analyst',
    'Computer operator',
    'Computer repair technician',
    'Computer scientist',
    'Computer analyst',
    'Data entry clerk',
    'Database administrator',
    'Data analyst',
    'Data designer',
    'Data scientist',
    'Hardware engineer',
    'Information systems technician',
    'IT assistant',
    'IT consultant',
    'Network analyst',
    'Network administrator',
    'Programmer',
    'Product manager',
    'Project manager',
    'Rapid prototyper',
    'Scrum master',
    'Security engineer',
    'Software analyst',
    'Software architect',
    'Software design',
    'Software engineer',
    'Software project manager',
    'Software quality analyst',
    'Software test engineer (Tester)',
    'Solution architect',
    'Support technician (Help Desk)',
    'System administrator',
    'Systems analyst',
    'Systems architect',
    'Test engineer',
    'User experience designer',
    'User interaction designer',
    'User researcher',
    'Video game developer',
    'Visual designer',
    'Virtual assistant',
    'Web developer',
    'Website administrator',
    'Bus driver',
    'Chauffeur',
    'Delivery (commerce)',
    'Emergency medical technician',
    'Motorman (tram/streetcar driver)',
    'Pay driver',
    'Racing driver',
    'Taxicab driver',
    'Test driver',
    'Train driver',
    'Truck driver',
    'Pilot',
    'Fleet Services Drivers',
    'Biologist',
    'Biomedical scientist',
    'Botanist',
    'Clinical pharmaceutical scientist',
    'Herpetologist',
    'Medical laboratory scientist',
    'Microbiologist',
    'Neuroscientist',
    'Physician',
    'Veterinarian',
    'Zoologist',
    'Aeronautical engineer',
    'Biomedical engineer',
    'Chemical engineer',
    'Civil engineer',
    'Computer engineer',
    'Educational technologist',
    'Electrical engineer',
    'Engineering technician',
    'Engineering technologist',
    'Mechanical engineer',
    'Petrochemical engineer',
    'Computational scientist',
    'Mathematician',
    'Statistics',
    'Demographic marketer',
    'Statistician',
    'Forensic scientist',
    'Government scientist',
    'Inventor',
    'Psychologist',
    'Research fellow',
    'School science technician',
    'Astronaut',
    'Archaeologist',
    'Astronaut',
    'Astronomer',
    'Biochemist',
    'Biologist',
    'Chemist',
    'Ecologist',
    'Forester',
    'Geographer',
    'Naturalist',
    'Oceanographer',
    'Paleontologist',
    'Pathologist',
    'Chemist',
    'Physicist',
    'Geographer',
    'Geologist',
    'Petroleum geologist',
    'Social science',
    'Anthropologist',
    'Economist',
    'Historian',
    'Linguist',
    'Political scientist',
    'Sociologist',
    'Urban planner',
    'Anesthesiologist',
    'Certified Registered Nurse Anesthetist',
    'Registered Respiratory Therapist',
    'Anesthesiologist Assistant',
    'Cardiologist',
    'Cardiology Physician Assistant',
    'Cardiac Scientist',
    'Cardiovascular Technologist',
    'Intensivist',
    'Neonatologist',
    'Critical Care Medicine Physician Assistant',
    'Critical Care Nurse Practitioner',
    'Critical Care Registered Nurse',
    'Critical Care Respiratory Therapist',
    'Dentist',
    'Dental Hygienist',
    'Dental Assistant',
    'Dental Technician',
    'Dermatologist',
    'Dermatology Physician Assistant',
    'Dietitian',
    'Emergency medicine',
    'Emergency physician',
    'Emergency Physician Assistant',
    'Flight Nurse',
    'Certified Emergency Registered Nurse',
    'Certified Emergency Registered Respiratory Therapist',
    'Emergency Medical Technician',
    'Endocrinologist',
    'Endocrinology Physician Assistant',
    'Gastroenterologist',
    'Gastroenterology Physician Assistant',
    'Genetic Counselor/Counsellor',
    'Geriatrician',
    'Geriatric Medicine Physician Assistant',
    'Occupational Therapist',
    'Haematologist',
    'Haematology Physician Assistant',
    'Medical Laboratory Technician',
    'Phlebotomist',
    'Nephrologist',
    'Nephrology Physician Assistant',
    'Dialysis Technician',
    'Neurologist',
    'Neurology Physician assistant',
    'Occupational Therapist',
    'Speech Language Pathologist',
    'Audiologist',
    'Neuropsychologist',
    'Oncologist',
    'Oncology Physician Assistant',
    'Radiation Therapist',
    'Ophthalmologist',
    'Optometrist',
    'Occupational Therapist',
    'Otolaryngologist',
    'Otorhinolaryngology Physician assistant',
    'Healthcare Chaplain',
    'Pathologist',
    'Pulmonologist',
    'Registered Respiratory Therapist',
    'General practitioner',
    'Primary care physician',
    'Internist',
    'Physician assistant',
    'Family nurse practitioner',
    'Pharmacist',
    'Neonatologist',
    'Pediatrician',
    'Pediatric Physician Assistant',
    'Neonatal Nurse Practitioner',
    'Pediatric Nurse Practitioner',
    'Pediatric Nurse',
    'Pediatric Respiratory Therapist',
    'Pharmacist',
    'Pharmacy technician',
    'Podiatric Surgeon',
    'Podiatrist',
    'Chiropodist',
    'Psychiatrist',
    'Psychiatry Physician Assistant',
    'Psychologist',
    'Psychiatric Nurse Practitioner',
    'Mental Health Nurse Practitioner',
    'Occupational Therapist',
    'Social Worker',
    'Mental Health Counselor',
    'Medical Officer of Health',
    'Environmental Health Officer',
    'Epidemiologist',
    'Public Health Nurse',
    'Orthopedic Physician',
    'Orthopaedic Physician´s Assistant',
    'Sport Psychologist',
    'Physical Therapist',
    'Occupational Therapist',
    'Physical Therapy Assistant',
    'Occupational Therapy Assistant',
    'Orthopaedic Technologist',
    'Chiropractor',
    'Biokineticist',
    'Athletic Trainer',
    'Yoga Instructor',
    'Massage Therapist',
    'Radiologist',
    'Radiology Physician Assistant',
    'Radiotherapist',
    'Radiographer',
    'CT Radiographer',
    'Interventional Radiographer',
    'Mammographer',
    'Neuroradiographer',
    'Medical Dosimetry Technologist',
    'Radiologist Practitioner Assistant',
    'Reporting Radiographer',
    'Sonographer',
    'Obstetrician',
    'Gynaecologist',
    'OB/GYN Physician Assistant',
    'Nurse-Midwife',
    'Midwife',
    'Lactation consultant',
    'General Doctor',
    'Bariatric Surgeon',
    'Cardiothoracic surgeon',
    'Cardiac Surgeon',
    'Hepatic Biliary Pancreatic Surgeon',
    'Neurosurgeon',
    'Podiatric Surgeon',
    'Surgery Physician Assistant',
    'Urologist',
    'Urology Physician Assistant',
]
